version: '3.0'
services:
  connectgpt-app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=development
    container_name: connectgpt-dev-app
    volumes:
      - .:/application
    networks:
      - connectgpt-network
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=1

  postgres:
    image: postgres:11
    container_name: postgres-gpt
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # volumes: 
    #   - ./backups/postgres:/var/lib/postgresql/data
    volumes:
    - postgres-data:/var/lib/postgresql/data
    networks:
      - connectgpt-network
networks:
  connectgpt-network:
volumes:
  postgres-data:
