default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_development_database_name

test:
  <<: *default
  database: your_test_database_name

production:
  <<: *default
  database: your_production_database_name
